import type { Metadata } from "next";
import { Geist, Geist_Mono, Cookie, Playwrite_US_Trad } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playwrite_us_trad = Playwrite_US_Trad({
  variable: "--font-playwrite-us-trad",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playwrite_us_trad.variable} antialiased h-screen`}
      >
        {children}
        <footer className="bottom-2 text-center w-full fixed"><small>Copyright © Elizabeth Tennant 2025</small></footer>
      </body>
    </html>
  );
}
